### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by IohannRabeson** [leezu/libzippp#1]
Hi, http://hg.markand.fr/libzip/ is broken!

**Comment by leezu** [comment]
This repo is a fork, though it appears the upstream repo has been deleted in the meantime. Please let me know the correct new upstream link and I'll edit the description accordingly

**Comment by IohannRabeson** [comment]
How can I know that? You better ask to @markand according to his pseudo he should probably know where is gone http://hg.markand.fr/libzip/...

**Comment by IohannRabeson** [comment]
Also @leezu I do not see this repo is a fork, I understand it's a kind of mirror, but it does not seem to be a "regular fork on github with a reference to the original project"

**Comment by markand** [comment]
Hi there!

Yes @leezu is right, I've given up on my original software that's why the link is definitely broken. Sorry for the inconvenience!

**Comment by leezu** [comment]
> but it does not seem to be a "regular fork on github with a reference to the original project"

@IohannRabeson that is because the original project has been deleted.
